add Lab1 3variant
maksimkha/FrontEnd pull request #1
Opened 2021-03-15 02:50 UTC by maksimkha

2021-03-22 19:20 UTC, gmltA requested changes
I don't see how you recover message history upon reconnection.

2021-03-22 19:20 UTC, gmltA commented on Lab1/Program.cs
> +            UdpClient sender = new UdpClient();
U sure you have to create sender each time you send a message?

2021-03-22 19:20 UTC, gmltA commented on Lab1/Program.cs
> +                            Console.WriteLine("Error with message order ");
So maybe fix it now?

2021-03-24 09:13 UTC, maksimkha commented on Lab1/Program.cs
> +            UdpClient sender = new UdpClient();
yeah, my fault

2021-03-24 09:15 UTC, maksimkha commented on Lab1/Program.cs
> +                            Console.WriteLine("Error with message order ");
added, now the initial idea is in sending "error message" to sender, when problem occurred. and when listener recieves this error message, he resends needed id

2021-03-25 19:13 UTC, gmltA approved these changes

2021-03-26 07:56 UTC, merged