Added lab3 implementation
maksimkha/FrontEnd pull request #3
Opened 2021-05-14 00:36 UTC by maksimkha

u can also check using this link https://agrexa-60b32.web.app/index.html

2021-05-14 17:55 UTC, gmltA requested changes

2021-05-14 17:55 UTC, gmltA commented on Lab3/public/account.html
> +            <label>Name:</label>
Label for what?

2021-05-14 17:55 UTC, gmltA commented on Lab3/public/item.html
> +              <button class="topbar__site-name" formaction="index.html">Agrexa</button>
That's not how you should make a link.

2021-05-14 17:55 UTC, gmltA commented on Lab3/public/styles.css
> +    zoom: 1;
?

2021-05-14 17:55 UTC, gmltA commented on Lab3/public/styles.css
> +    -ms-transform: translateX(26px);
?

2021-05-14 20:01 UTC, maksimkha commented on Lab3/public/item.html
> +              <button class="topbar__site-name" formaction="index.html">Agrexa</button>
yeap, changed 'form' to 'a'

2021-05-14 20:01 UTC, maksimkha commented on Lab3/public/styles.css
> +    zoom: 1;
unnecessary zoom is removed

2021-05-14 20:02 UTC, maksimkha commented on Lab3/public/styles.css
> +    -ms-transform: translateX(26px);
fixed

2021-05-14 20:03 UTC, maksimkha commented on Lab3/public/account.html
> +            <label>Name:</label>
can't get this error. i have labels for labeling my input fields. am i doing smthing wrong?

2021-05-15 19:49 UTC, gmltA requested changes
And now you also have to tell me where this `zoom: 1` came from.

2021-05-15 19:49 UTC, gmltA commented on Lab3/public/account.html
> +            <label>Name:</label>
Your labels are currently labeling nothing because you have to link between them and corresponding inputs.

2021-05-17 01:46 UTC, maksimkha commented
got it, so i changed my acc page. and those 'zoom: 1' were like a bunch of brainless ideas of trying to adapt my views to both screen sizes, forgot to remove those

2021-05-18 20:06 UTC, gmltA approved these changes
That's a <kbd>6</kbd>.

2021-05-18 20:09 UTC, merged